### ISSUE TITLE
It failed to download most of my emails

### ISSUE THREAD

**Issue by Keith-S-Thompson** [WeeJeWel/node-google-backup#1]
I ran the tool as specified:
```
npx -y --username myname@gmail.com --password mypassword --filepath mydirectory
```

It completed in about 12 minutes, but it downloaded only a fraction of my email messages, apparently the earliest ones. It appears to have downloaded all of my `sent` messages, but only the first 10% or so of my `received` messages.

I've had my gmail account since 2006-08-08. The last downloaded `received` message is dated 2014-07-18. I got 10822 messages, `1.eml` through `18216.eml` with gaps.

A [comment](https://news.ycombinator.com/item?id=41212551) on Hacker News shows that at least one other person had the same problem:

> Looks handy, although it only grabbed like the first 2 years of gmail for me, out of 20. Re-running the docker image did not help.

As far as I can tell it downloaded by calendar and contacts correctly (probably because they're a much smaller amount of data), though I haven't directly confirmed that.

**Comment by WeeJeWel** [comment]
Hm that’s odd. It does download ‘[Gmail]\All Mail’. Maybe somehow that inbox is quite empty in your case?

**Comment by otonoton** [comment]
Same issue here for me as well.

**Comment by Keith-S-Thompson** [comment]
My guess is that it's a limitation on Google's end. My `All Mail` folder currently has about 125,000 messages. How big is yours?

Perhaps I can help debug the issue.

If you add some logging statements to `GoogleBackupMail.mjs` (either on a temporary branch or in a comment on this issue), I'll run it on my system and report the results.

**Comment by otonoton** [comment]
355k in my All Mail.

**Comment by Keith-S-Thompson** [comment]
More information:

Ubuntu 22.04.4 LTS

The system has nodejs 12.22.9, which didn't work. I installed 22.6.0 from source.

I get a warning, which I'm assuming is mostly harmless:
```
(node:35800) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

**Comment by WeeJeWel** [comment]
I cannot really debug from here. Maybe you can add some logs to the code yourself and find out what's wrong?

**Comment by Keith-S-Thompson** [comment]
I've added some logging code, and I have a hunch what might be going on.
I don't know either IMAP or JavaScript well enough to be sure.

In `GoogleBackupMail.mjs`:
```
        // Search for new messages
        const messages = await this.imapClient.search([['UID', `${start}:${end}`]], fetchOptions);
```
Apparently IMAP UIDs are not contiguous. The first call, with start=1 and end=100, yields 96 messages. The next yields 69. And so forth. A search with start=1201 and end=1300 yields just 2 messages.

The last search executed for `All Mail`, with start=18217 and end=18316, yields 0 messages -- but they're from about 10 years ago.

Presumably there are still more messages, but it stops when a range of 100 UIDs happens to contain no messages.

I'm trying again with batchSize=1000, still running as I write this. That's not a solution, but it seems to be working; I'm at least getting more messages than with batchsize=100. (It's still possible that a search over a range of 1000 UIDs could turn up empty, but it's less likely.)

If I'm right, you need to use some criterion other than search yielding 0 messages to determine that you're done.

**Comment by Keith-S-Thompson** [comment]
Confirmed, setting batchSize=1000 let me get (what appears to be) all my emails.

I got 135234 emails, with UIDs from 1 to 183053. The largest gap is 102 missing UIDs; `18216.eml` is followed by `18319.eml`. Those messages were just 26 minutes apart. I have no idea why there are gaps, or how Google assigns UIDs.

Again, setting batchSize=1000 is not the right solution; there needs to be some reliable way to detect that we've seen all the messages.

**Comment by WeeJeWel** [comment]
That’s a great find! I will think about a solution. There is a ‘new’ command in imap so maybe we can use that to find the largest message ID.

**Comment by WeeJeWel** [comment]
@Keith-S-Thompson @otonoton Can you try this branch and let me know if this fixes your issue?

https://github.com/WeeJeWel/node-google-backup/tree/fix/get-newest-uid

**Comment by Keith-S-Thompson** [comment]
I'm running into some issues probably due to my inexperience with JavaScript and node.js rather than any problem with this software.

I'll contact you by email rather than cluttering this ticket.

**Comment by Keith-S-Thompson** [comment]
I didn't know how to run it from a local copy. The solution is to do the following from a checked-out git repo:
```
npm install
npm link
npx -y google-install ...
```

I did that and ran with the `fix/get-newest-uid` branch, and it worked when I ran it with filepath set to a new empty directory.

But when I tried again with an existing directory containing a large number of emails, I got an error as it was trying to determine the max UID of the existing `*.eml` files:
```
file:///home/kst/git/node-google-backup/lib/GoogleBackupMail.mjs:115
        return Math.max(...uids);
                    ^

RangeError: Maximum call stack size exceeded
    at file:///home/kst/git/node-google-backup/lib/GoogleBackupMail.mjs:115:21
    at async GoogleBackupMail.downloadBox (file:///home/kst/git/node-google-backup/lib/GoogleBackupMail.mjs:105:23)
    at async GoogleBackupMail.createBackup (file:///home/kst/git/node-google-backup/lib/GoogleBackupMail.mjs:81:7)
    at async GoogleBackup.backupMail (file:///home/kst/git/node-google-backup/lib/GoogleBackup.mjs:60:5)
    at async Promise.all (index 0)
    at async file:///home/kst/git/node-google-backup/bin/google-backup.mjs:30:1
```

(Is it possible that `Math.max` is recursive??)

**Comment by Keith-S-Thompson** [comment]
This change avoids the stack overflow. (You could also drop the special case check for `uids.length === 0`.)
```
diff --git lib/GoogleBackupMail.mjs lib/GoogleBackupMail.mjs
index 90829a2..7821c7c 100644
--- lib/GoogleBackupMail.mjs
+++ lib/GoogleBackupMail.mjs
@@ -112,7 +112,15 @@ export default class GoogleBackupMail {
           return 0;
         }
 
-        return Math.max(...uids);
+        var maxUID = 0;
+        for (const uid of uids) {
+            if (uid > maxUID) {
+                maxUID = uid;
+            }
+        }
+        return maxUID;
+
+        // return Math.max(...uids);
       });
 
     try {
```

Apparently the problem is not that `Math.max` is doing something silly, it's that the entire `uids` list is being passed to `Math.max` **on the stack**. (Maybe there's a way to pass it by reference?)

Similar problem reported here: https://github.com/nodejs/node/issues/43043

**Comment by WeeJeWel** [comment]
Haha! I never expected that to become a problem.

Fixed in https://github.com/WeeJeWel/node-google-backup/commit/004d9a19310f4391440b346e4b11ba52bd902d54.

**Comment by WeeJeWel** [comment]
Published as `google-backup@1.2.0`.

**Comment by Keith-S-Thompson** [comment]
You get the maximum value by sorting the list and selecting the first element.

I haven't tried the new version or done any timings, but that's going to be O(N log N) (assuming JavaScript's `sort` is sane), while a linear scan is O(N). It's an in-memory operation, but I imagine it might be significant when the list has 100,000 or so elements, as it does for me.

**Comment by WeeJeWel** [comment]
Honestly I doubt you’ll really notice it. But feel free to make a PR that optimizes it.

**Comment by Keith-S-Thompson** [comment]
I just measured it. The sort took about 0.8 seconds. I don't think I'll bother submitting a PR (though I would encourage you to change it next you're doing a significant update).

**Comment by otonoton** [comment]
@WeeJeWel I updated the docker image and re-ran the import from scratch. It still only downloads old mails from 2004-2007, plus anything new that arrived since the last run. It also does not appear to have any folder or label structure applied, so I just get mostly spam downloaded that's new.

**Comment by WeeJeWel** [comment]
> @WeeJeWel I updated the docker image and re-ran the import from scratch. It still only downloads old mails from 2004-2007, plus anything new that arrived since the last run. It also does not appear to have any folder or label structure applied, so I just get mostly spam downloaded that's new.

Try removing all previously downloaded emails and retry.

**Comment by otonoton** [comment]
That is what I meant by "re-ran the import from scratch". I started over with no mails at all.

**Comment by WeeJeWel** [comment]
Hm sorry, I don’t know why that happens then.

**Comment by WeeJeWel** [comment]
> I just measured it. The sort took about 0.8 seconds. I don't think I'll bother submitting a PR (though I would encourage you to change it next you're doing a significant update).

This is now fixed.

**Comment by WeeJeWel** [comment]
@otonoton Could you try running this branch? I've rewritten the download logic to download all mailboxes.

https://github.com/WeeJeWel/node-google-backup/tree/feature/download-all-boxes

**Comment by Keith-S-Thompson** [comment]
> 404 - page not found
> Cannot find a valid ref in `feature/download-all-boxes`

**Comment by WeeJeWel** [comment]
I’ve already merged to main and deleted the branch. Please try the latest release.

**Comment by otonoton** [comment]
@WeeJeWel Still having this problem with the latest container pull from ghcr.io.

All mail from my work "google apps for business" account is downloaded, but only ancient messages from my personal gmail get downloaded.

**Comment by WeeJeWel** [comment]
Hm. I'd like to help you, but without either access to your account, or you doing some debugging yourself, I really don't know why this happens.
